FROM node:24-alpine AS base
RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

WORKDIR /app
COPY --chown=nextjs:nodejs . .

RUN --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile

USER nextjs
CMD ["pnpm", "dev:web"]
